"""Make last_connection nullable

Revision ID: cc3a49594694
Revises: 
Create Date: 2024-03-16 13:28:26.288817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3a49594694'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_participant')
    op.drop_table('chats')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('contact', sa.INTEGER(), nullable=False),
    sa.Column('added_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['contact'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('username', sa.VARCHAR(length=40), nullable=False),
    sa.Column('password', sa.VARCHAR(length=45), nullable=True),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('picture_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.Column('last_connection', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('chat', sa.INTEGER(), nullable=False),
    sa.Column('sender_user', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('sent_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['sender_user'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('is_group', sa.BOOLEAN(), nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('chat_participant',
    sa.Column('chat_participant_id', sa.INTEGER(), nullable=False),
    sa.Column('chat', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('joined_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_participant_id')
    )
    # ### end Alembic commands ###
