services:

  chat_api:
    build:
      context: ./app/chat_api
      dockerfile: Dockerfile
    env_file:
      - ./app/chat_api/.env
    volumes:
      - ./app/chat_api:/app
    ports:
      - 8080:8080
      - 5678:5678
    command: /app/startup_local.sh
    depends_on:
      - db
      - redis

  chat_client:
    build:
      context: ./app/chat_client
      dockerfile: Dockerfile.dev
    env_file:
      - ./app/chat_client/.env
    volumes:
      - ./app/chat_client:/app
      - /app/node_modules/
      - chat_app_files:/app/public/files
    ports:
      - 5173:5173

  # chat_client_prod:
  #   build:
  #     context: ./app/chat_client
  #     dockerfile: Dockerfile.prod
  #   env_file:
  #     - ./app/chat_client/.env
  #   volumes:
  #     - ./app/chat_client/dist:/usr/share/nginx/html
  #     - chat_app_files:/usr/share/nginx/html/files
  #   ports:
  #     - 8000:80

  fileserver:
    build:
      context: ./app/fileserver
      dockerfile: Dockerfile
    volumes:
      - ./app/fileserver:/app
      - chat_app_files:/app/files
    env_file:
      - ./app/fileserver/.env
    ports:
      - 8090:8000
      - 5679:5678
    command: /app/startup_local.sh

  mailer_api:
    build:
      context: ./app/mailer
      dockerfile: Dockerfile.api
    volumes:
      - ./app/mailer:/app
    env_file:
      - ./app/mailer/.env
    ports:
      - 8100:8000
      - 5680:5678
    command: /app/startup_local.sh

  mailer_celery:
    build:
      context: ./app/mailer
      dockerfile: Dockerfile.celery
    volumes:
      - ./app/mailer:/app
    env_file:
      - ./app/mailer/.env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_admin
    volumes:
      - ./app/scripts/postgress-init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - chat_app_db:/var/lib/postgresql
    ports:
      - 5435:5432

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    volumes:
      - chat_app_redis:/data
    ports:
      - 6379:6379

volumes:
  chat_app_db:
  chat_app_redis:
  chat_app_files:
