version: "3.9"

services:

  chat_api:
    build:
      context: ./chat_api
      dockerfile: Dockerfile
    env_file:
      - ./chat_api/.env
    volumes:
      - ./chat_api:/app
    ports:
      - 8080:8080
      - 5678:5678
    command: /app/startup_local.sh
    depends_on:
      - db

  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    volumes:
      - ./fileserver:/app
    env_file:
      - ./fileserver/.env
    ports:
      - 8090:8000
      - 5679:5678
    command: /app/startup_local.sh

  mailer_api:
    build:
      context: ./mailer
      dockerfile: Dockerfile.api
    volumes:
      - ./mailer:/app
    env_file:
      - ./mailer/.env
    ports:
      - 8100:8000
      - 5680:5678
    command: /app/startup_local.sh

  mailer_celery:
    build:
      context: ./mailer
      dockerfile: Dockerfile.celery
    volumes:
      - ./mailer:/app
    env_file:
      - ./mailer/.env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_admin
    volumes:
      - ./scripts/postgress-init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - chat_app_db:/var/lib/postgresql
    ports:
      - 5435:5432

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    volumes:
      - chat_app_redis:/data
    ports:
      - 6379:6379

volumes:
  chat_app_db:
  chat_app_redis:
