FROM python:3.12-alpine

WORKDIR /app

COPY ./ /app

RUN pip install -r requirements.txt --no-cache

# turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# this is so celery can find the modules
ENV PYTHONPATH=/app/src

CMD ["celery", "-A", "src.celery_app.celery_app", "worker", "--loglevel=info"]